language: python
python: '3.8'
env:
  global:
  - GITLAB_API_URL=https://gitlab.com/api/v4
  - secure: "KzqcGsCYDfb+A1WjFyilvI55Ne7e7hNONi/Vr2trEc958rqR8mrASGUVgDh39ZbEM7Qm1hVKye6FvYOMb8UE8sPtOkt6qdObuwwkulj6XQQ93LWcqk1k2OwMoqX/0X2EAlt4Aah4grLtMhKFPqDpEkG98pkNIseBbIDl9XXs0ntfLjUvrUTUzhIR9kHBJprqx8GzjdePJi2BPng6I5uzcDCkLYIcoHOws3FyOQwShtHyHjTdjpmerxxoXb/NYpGbbHAFRtrzIPU3m0dmooxWkLZueVl2JOCJ4X9QzTbG5FOUaAN5embBIqzf0BvkWpaY3YgJuF+ZaOOJ2oSG7VxRT5ZuQwe+MQA60vql5jfzagh2DblOkyiRfvxCUEvxVNT6UeJjMiHgGDIi85vT/Rto2kQPILBbjQwm/sgQ8FiTPvs1JKO2xg66LhTrAMorMbE27/AnCtG4YdlA8wXiO3DtNca7XgajYKQlloGPXYKLOZlCj2oLqdQaP9FyXmUn2qlBsA47LBlKIupU3CAoZyWywtV5IEKTue5urzhQda2SsygIgjQhP5nmPQADrVp3Cu/eTPlLmdMWHahWenNDhhotLfv1FWGQlonDKSYNYYVTYQCPq027/ST543lz58jWeqJ/n125vRGXt7K/8NvKHbOQbkpKVxh8/2PFjlSKQEZE0Ec="

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq python-apt python-pycurl

install:
- pip install ansible ansible-lint
- ansible --version

script:
- ansible-lint tasks/*.yml
- |
  ANSIBLE_ROLES_PATH=$(pwd)/.. ansible-playbook \
    -i tests/hostfile \
    -e "role_name=ansible-gitlab-ci-variables" \
    -e "gitlab_api_url=$GITLAB_API_URL" \
    -e "gitlab_token=$GITLAB_TOKEN" \
    -e "gitlab_ci_check_unknown=false" \
    tests/gitlab-ci-variables.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
